name: Documentation feedback
about: Provide feedback on a page on our website
title: ""
issue_body: true
inputs:
  - type: description
    attributes:
      value: |
        Thanks for opening an issue to provide feedback on our website/documentation.

        Please note, this form is not for reporting bugs with running Home Assistant or its integrations.
        Those bugs should be reported in the [Home Assistant Core issue tracker][core].

        [core]: https://github.com/home-assistant/core/issues
  - type: textarea
    attributes:
      label: Feedback
      required: true
      description: >-
        Please be sure to provide feedback as clear as possible. Describe what
        you think is incorrect or can be improved, and try to provide a
        suggestion on how you think it can be improved or fixed.
  - type: description
    attributes:
      value: |
        ## Details
  - type: input
    attributes:
      label: URL
      required: true
      placeholder: "http://www.home-assistant.io/..."
      description: >
        A URL with a link to the page you are providing feedback for.
  - type: input
    attributes:
      label: Version
      required: false
      placeholder: "e.g., 2021.2.0"
      description: >
        Current version of the documentation. This usually matches the Home
        Assistant Core release version, and can be found at the bottom of the
        page.
  - type: description
    attributes:
      value: |
        ## Additional information
  - type: description
    attributes:
      value: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
